name = "teo-duel"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "teo"
database_id = "257af718-b773-4c94-81c5-76c72850f309"
